- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP traffic
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow HTTPS traffic
  community.general.ufw:
    rule: allow
    port: 443