replicaCount: 1

image:
  repository: java-app-frontend
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80

ingress:
  enabled: true
  className: nginx
  host: javaapp.local
  path: /
  pathType: Prefix
