server {
    listen 80;
    server_name kibana.julia-b.work;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kibana.julia-b.work;

    ssl_certificate /etc/letsencrypt/live/kibana.julia-b.work/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/kibana.julia-b.work/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

    location / {
        proxy_pass http://localhost:5601;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # WebSocket support for Kibana
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
